name: 04-Workflow Actions

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - name: CheckOut Code
        uses: actions/checkout@v4

      # set up node
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '24.x'
      # Installing Dependencies
      - name: Install Dependencies
        run: npm ci