name: 04-Workflow Actions

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - name: CheckOut Code
        uses: actions/checkout@v4
        
      # Listing the folder
      - name: Printing Folders
        run: ls -lh

